### ISSUE TITLE
Inconsistent licenses for some plugins

### ISSUE THREAD

**Issue by chayleaf** [maubot/plugins.maubot.xyz#6]
- https://github.com/maubot/echo; MIT in maubot.yaml != AGPL-3.0-or-later in repo
- https://github.com/maubot/songwhip; AGPL-3.0-or-later in maubot.yaml != MIT in repo
- https://github.com/williamkray/maubot-kickbot; None in maubot.yaml != MIT in repo
- https://github.com/williamkray/maubot-chatgpt; None in maubot.yaml != MIT in repo
- https://github.com/williamkray/maubot-createroom; None in maubot.yaml != MIT in repo
- https://github.com/williamkray/maubot-gifme; None in maubot.yaml != MIT in repo
- https://git.skeg1.se/vondassendorf/maubot_mauhelp; MIT in maubot.yaml != None in repo
- https://github.com/williamkray/maubot-join; None in maubot.yaml != MIT in repo
- https://github.com/SAPUCC/inviterbot; GPLv3 in maubot.yaml != GPL-3.0-or-later in repo
- https://github.com/ggogel/SocialMediaDownloadMaubot; MIT in maubot.yaml != None in repo
- https://codeberg.org/lomion/tmdb-bot; AGPL 3.0 in maubot.yaml != AGPL-3.0-or-later in repo
- https://github.com/williamkray/maubot-welcome; None in maubot.yaml != MIT in repo

**Comment by williamkray** [comment]
This repo is really just an index of plugins, and doesn't control their code or their licenses... As maintainer of some of those plugins I can fix that where they are managed, but I don't think this is the place for this issue.

**Comment by chayleaf** [comment]
Two of these plugins are official, so it'd be nice for at least those cases to be fixed

**Comment by tulir** [comment]
Looks like echo was a mistake in this repo, songwhip was a mistake in maubot.yaml

The LICENSE file is usually authoritative over maubot.yaml, so when filling this repo I only looked at the license file. Added the two that only specified the license in maubot.yaml now (help and social media download).

"GPLv3" and "AGPL 3.0" aren't valid SPDX license identifiers, but looking at the headers in the python files, inviterbot seems to have the or later clause (https://github.com/SAPUCC/inviterbot/blob/main/inviter/bot.py#L8) while tmdb doesn't (https://codeberg.org/lomion/tmdb-bot/src/branch/master/tmdb/database.py#L5)
